### ISSUE TITLE
Module not found: Error: Can't resolve './Counter.bs' 

### ISSUE THREAD

**Issue by zhangmaku** [therewillbecode/haskell-poker#5]
ERROR in ./app/components/Profile.js
Module not found: Error: Can't resolve './Counter.bs' in '/home/user/haskell-poker/client/app/components'
 @ ./app/components/Profile.js 3:18-41
 @ ./app/containers/ProfileContainer.js
 @ ./app/components/App.js
 @ ./app/containers/AppContainer.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
｢wdm｣: Failed to compile.

**Comment by therewillbecode** [comment]
Thanks for creating this issue. I am working on it.

**Comment by therewillbecode** [comment]
Fixed in latest master branch.
